### PR TITLE
feat: support `-out` flag for the `plan` command

### PR DESCRIPTION
**Pull request by v1v**
Does what it says in the tin, aka enable https://developer.hashicorp.com/terraform/cli/commands/plan#out-filename

### CODE REVIEW

**Review by amannocci — DISMISSED** [review]

**Comment by reakaleek** [comment]
What happens when you don't provide a resource name? e.g. if you only run `terranova plan --out tf.plan`?

**Comment by v1v** [comment]
See [`53c3894` (#101)](https://github.com/elastic/terranova/pull/101/commits/53c389459e6e72a08a17909dde307a2c06f06fa0)

**Comment by reakaleek** [comment]
> See [`53c3894` (#101)](https://github.com/elastic/terranova/pull/101/commits/53c389459e6e72a08a17909dde307a2c06f06fa0)

IMO we should keep the "normal" behaviour if we are working with a single resource path.

This will be easier in the usage:

```
terranova plan oblt-actions --out tf.plan
terranova apply oblt-actions tf.plan
```

Otherwise, the plan file will be in an unexpected place.

IIUC, with the current implementation it would be something like

```
terranova plan repos/oblt-actions --out tf.plan
terranova apply oblt-actions tf.plan/repos/oblt-actions-tfplan
```

**Comment by v1v** [comment]
> IIUC, with the current implementation it would be something like

I think it will use the `out` as the location where those files are stored:

```
terranova plan repos/oblt-actions --out tf.plan
terranova apply oblt-actions tf.plan/oblt-actions-tfplan
```


Let's then agree what we expect:

1) If no resources, what do we do?
2) If resources, what do we do?

**Comment by reakaleek** [comment]
What do you think about using the resource path as the "working dir"?

e.g. we have the resource folders

```
.
└── conf/
    └── resources/
        ├── repos/
        │   └── apm-agent-java
        └── projects/
            └── serverless
```

if you run `terranova plan --out tf.plan`
then, a `tf.plan` file is created in every path

e.g.
```
conf/resources/repos/apm-agent-java/tf.plan
conf/resources/projects/serverless/tf.plan
```

Then, if you run `terranova apply tf.plan`, it would the search for the file internally.

**Comment by v1v** [comment]
> What do you think about using the resource path as the "working dir"?

I think that's double, let me take a swing

**Comment by v1v** [comment]
I'm glad to say this is now working out of the box, I forgot that the current-dir is already set,


```bash
$ ../terranova/dist/terranova plan --out plan-tf apm-agent-java                     
⇒ Generating plan: 
⇒   -- path: conf/resources/apm-agent-java
....

$ ls -l conf/resources/apm-agent-java/plan-tf 
-rw-r--r--  1 vmartinez  staff  21247 Oct 14 13:58 conf/resources/apm-agent-java/plan-tf 
```

```bash
$ ../terranova/dist/terranova plan --out plan-tf
⇒ Generating plan: opbeans-loadgen
⇒   -- path: conf/resources/opbeans-loadgen
...
⇒ Generating plan: opbeans-ruby
⇒   -- path: conf/resources/opbeans-ruby
....

$ find . -name plan-tf -ls
44349935       24 -rw-r--r--    1 vmartinez        staff                8518 Oct 14 14:01 ./conf/resources/opbeans-loadgen/plan-tf
44350016       40 -rw-r--r--    1 vmartinez        staff               20162 Oct 14 14:01 ./conf/resources/opbeans-ruby/plan-tf
```

**Comment by reakaleek** [comment]
Oh, interesting.

**Review by reakaleek — APPROVED** [review]

**Comment by amannocci** [comment]
WDYT about the second option?

**Comment by v1v** [comment]
> WDYT about the second option?

Can you elaborate on how the second option works? I could not understand it

**Comment by amannocci** [comment]
Instead of creating a plan per resource group, we can create a single `Terranova` plan file.
The `terranova` plan file contains each resource group `terraform` plan.
When applying, we have a consistent file where we iterate over each resource group and apply each plan.
The outcome is the same, except that we have only one plan file instead of many in each resource group location.

**Comment by v1v** [comment]
> Instead of creating a plan per resource group, we can create a single Terranova plan file.

Gotcha, will this plan work with `terraform` out of the box?

> The outcome is the same, except that we have only one plan file instead of many in each resource group location.

Your idea is to make this integration easier with `terranova apply`?

What if the single plan contains some resources that are not correct, will this plan stop processing the remaining resources? With one file per resource group, I think that won't be a problem if we use https://github.com/elastic/terranova/issues/38, but I don't know how will that work with one file with all the resources

**Comment by reakaleek** [comment]
Iterating through all resource folders and adding the plan to the relative folder feels more "native" to me.
Especially, because it's already implemented that way.

**Comment by amannocci** [comment]
> Gotcha, will this plan work with terraform out of the box?

It should work in the same way. 

> Your idea is to make this integration easier with terranova apply?

It will be easier in terms of generation and avoid the discovery phase which could be faster in large setup.

> What if the single plan contains some resources that are not correct, will this plan stop processing the remaining resources? With one file per resource group, I think that won't be a problem if we use https://github.com/elastic/terranova/issues/38, but I don't know how will that work with one file with all the resources

It will behave the same. We will still iterate over each resource group and invoke individual terraform plan.
It avoid the per resource group terraform plan file generation.
The proposal is to aggregate all plans within a single file.
The execution order and outcome remains the same.

**Comment by reakaleek** [comment]
Can we merge this?

I understand the concerns, but if I understand correctly, just adding the `--out` as it is now will also make it easier to integrate it with the `apply` command.

Almost no changes are needed because the `apply` command also iterates over every resource folder.

**Comment by amannocci** [comment]
In term of outcome, it will be the same.
However, I prefer the second approach to prepare the ground for future features.
Implementing a terranova plan file will allow to compute a graph of dependencies without the exploration phase.

**Comment by v1v** [comment]
> However, I prefer the second approach to prepare the ground for future features.

Do you plan to do so? Otherwise, we don't have the time to do it on our end. @amannocci , can we merge this? Or do you prefer to wait for using the second approach instead? Just want to be sure how we can unblock our current work

> In term of outcome, it will be the same.

If the same outcome, then it can be refactored in the future, I guess.

**Pull request closed without merging**
