### PR TITLE
chore: don't format on save

### PR DESCRIPTION
**Pull request by amannocci**
## What is the change being made?

* Specific local configuration for Zed IDE.

## Why is the change being made?

* Avoid re-format on each save.

### CODE REVIEW

**Review by v1v — APPROVED** [review]
Wonder whether these settings should be outside of the project and use `.editorconfig` if that's the defacto standard?

**Comment by v1v** [comment]
https://github.com/zed-industries/zed/issues/8534 ... I'm not sure if adding these settings for a specific IDE is the way to go

**Comment by amannocci** [comment]
As of today, the property `format_on_save` is specific to the Zed IDE and can't be configured using the `editorconfig`.

**Comment by v1v** [comment]
> As of today, the property format_on_save is specific to the Zed IDE and can't be configured using the editorconfig.

Is it possible to configure that settings at the HOME level? Similarly done with other tools such as `~/.gitconfig`

**Comment by amannocci** [comment]
> > As of today, the property format_on_save is specific to the Zed IDE and can't be configured using the editorconfig.
> 
> Is it possible to configure that settings at the HOME level? Similarly done with other tools such as `~/.gitconfig`

There is the ability to set it [globally](https://zed.dev/docs/configuring-zed#global-settings).
However, in this case, it's a project format issue with the template mixed format.

**Comment by v1v** [comment]
All good if you wanna merge this - though I think the issue about IDEs don't using a standard properties file is certainly not good.

**Pull request merged**
